#!/usr/bin/env python3
"""Pixel favicons for library.wuld.ink -- the front door, the flagship, the five wings.

FAMILY. Siblings of wuld.ink/favicon.svg (K24a): 16x16 viewBox, shape-rendering="crispEdges",
near-black #0a0a0a ground, no curves, no anti-aliasing, no gradients. Where the house mark is a
crimson glyph on black, these invert the emphasis the way the layer's own chin does: off-white
chrome with exactly ONE lit element in the library's crimson. One LED per instrument.

VOCABULARY. Each mark is a fragment of the diagram language the pages already contain -- nodes and
edges, as in the mechanism web and the dependency graph -- not a picture of the wing's subject.
An argument library is not an advocacy poster, and a 16px pictograph of any of these topics would
be a claim the corpus does not make.
"""
import subprocess, sys, os
print('$ ' + ' '.join([sys.executable] + sys.argv) + '\n')

BG, FG, ACC = '#0a0a0a', '#e8e4dd', '#ef3a58'   # ground, chrome, the library's crimson (K314)

def R(x, y, w, h, c=FG): return (x, y, w, h, c)

ICONS = {
 # the index: six libraries, one lit
 'libraries': ("The Refusal Libraries — six cells, an index", [
    R(3,1,4,4), R(9,1,4,4, ACC),
    R(3,6,4,4), R(9,6,4,4),
    R(3,11,4,4), R(9,11,4,4)]),
 # the corpus: five tiers, stratified
 'combined': ("the flagship — the five-tier ladder", [
    R(2,1,12,2, ACC), R(2,4,10,2), R(2,7,8,2), R(2,10,6,2), R(2,13,4,2)]),
 # an opening, not a terminus
 'right-to-die': ("Right to Die — a doorway standing open", [
    R(2,2,12,2), R(2,4,2,11), R(12,4,2,11), R(7,12,2,3, ACC)]),
 # one stem, two available branches
 'abortion': ("Abortion — a stem that forks; both branches present", [
    R(1,7,7,2), R(8,3,2,10), R(10,2,4,4), R(10,11,4,4, ACC)]),
 # a relation with no direction and no ranking
 'transgenderism': ("Transgenderism — two nodes, one edge, no arrowhead either way", [
    R(1,6,4,4), R(5,7,6,2), R(11,6,4,4, ACC)]),
 # peers, and no centre
 'anthropocentrism': ("Anthropocentrism — four peers around an empty centre", [
    R(6,1,4,4), R(1,6,4,4), R(11,6,4,4, ACC), R(6,11,4,4)]),
 # the boundary drawn wider than one
 'veganism': ("Veganism — a boundary enclosing more than one", [
    R(1,3,14,2), R(1,11,14,2), R(1,5,2,6), R(13,5,2,6),
    R(4,7,3,3), R(9,7,3,3, ACC)]),
}

HEAD = ('<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!--\n  library.wuld.ink favicon — {desc}\n'
        '  Sibling of wuld.ink/favicon.svg (K24a): 16x16, crispEdges, #0a0a0a ground.\n'
        '  Chrome #e8e4dd, one lit element in the library crimson #ef3a58.\n'
        '  Generated by icons/gen_icons.py — edit the grid there, never the SVG.\n-->\n'
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" shape-rendering="crispEdges">\n'
        '  <rect width="16" height="16" fill="{bg}"/>\n')

for name, (desc, rects) in ICONS.items():
    body = ''.join('  <rect x="%d" y="%d" width="%d" height="%d" fill="%s"/>\n' % r for r in rects)
    for x, y, w, h, c in rects:
        assert 0 <= x and x + w <= 16 and 0 <= y and y + h <= 16, (name, x, y, w, h)
    svg = HEAD.format(desc=desc, bg=BG) + body + '</svg>\n'
    head = svg.split('-->')[0]
    assert '--' not in head.split('<!--',1)[1], (name, 'double hyphen inside the XML comment')
    open(name + '.svg', 'w', encoding='utf-8').write(svg)
    for px in (16, 32, 64):
        subprocess.run(['rsvg-convert', '-w', str(px), '-h', str(px), '-o',
                        f'{name}.{px}.png', name + '.svg'], check=True)
    print(f'{name:20s} {len(rects)} rects  {desc}')
