#!/usr/bin/env python3
"""icons_regen_check.py -- the served favicons are exactly what icons/gen_icons.py draws. L1 (2026-09-25).

Every site/icon-*.svg says "Generated by icons/gen_icons.py -- edit the grid there, never the SVG", and
until L1 no repo tracked that script. This runs it in a scratch directory (it writes <name>.svg plus
16/32/64 px PNGs into its working directory, and needs rsvg-convert on PATH) and requires the SVGs it
draws to be, name for name and byte for byte, the site/icon-<name>.svg files. The PNGs are not served
and are discarded. Never run gen_icons.py from the repo root: it would drop its outputs there.

  python3 tools/icons_regen_check.py [ROOT]    # exit 1 on any difference; ROOT defaults to this repo
"""
import glob, hashlib, os, shutil, subprocess, sys, tempfile

REPO = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
d = tempfile.mkdtemp(prefix="icons_regen_")
try:
    shutil.copyfile(os.path.join(REPO, "icons", "gen_icons.py"), os.path.join(d, "gen_icons.py"))
    subprocess.run([sys.executable, "gen_icons.py"], cwd=d, check=True, capture_output=True)
    drawn = {os.path.basename(p)[:-4]: open(p, "rb").read() for p in glob.glob(os.path.join(d, "*.svg"))}
finally:
    shutil.rmtree(d)
served = {os.path.basename(p)[5:-4]: open(p, "rb").read()
          for p in glob.glob(os.path.join(REPO, "site", "icon-*.svg"))}
bad = 0
for name in sorted(set(drawn) | set(served)):
    a, b = drawn.get(name), served.get(name)
    ok = a is not None and a == b
    bad += not ok
    detail = ("not drawn by gen_icons.py" if a is None else
              "not served" if b is None else hashlib.md5(b).hexdigest())
    print("  %s  %-18s %s" % ("SAME" if ok else "DIFF", name, detail))
print("ICONS: %d of %d served favicons regenerate byte for byte" % (len(served) - bad, len(served))
      if not bad else "ICONS: RED -- %d difference(s)" % bad)
sys.exit(1 if bad else 0)
