#!/usr/bin/env python3
"""pin_labels_ld3.py -- move the release labels with the LD3 pin (the design lane's flagship marks, 2026-09-26; the
K362 law). pin_labels_l5.py stays as L5 left it: its entry text describes a content cut, and this release is not one.

This moves every label the pin owns, each edit anchored exactly once, from v4.1.3 to the new pin:
  README.md               the pin table (version, md5, size), the libraries row, the 'Stable at' paragraph's opening
                          and its canon file, the canon file named in the integrity and layout paragraphs, the BibTeX
  CITATION.cff            version, date-released
  site/libraries/index.html   the flagship card's 'pinned vX' badge (the one served label)
  CHANGELOG.md            a release entry at the top, with the md5 table and his word verbatim

The new md5 and bytes are read from the working site/combined.html; the old ones must be what the files say now.

  python3 tools/pin_labels_ld3.py --version v4.1.4 --date 2026-09-26 --canon 38.36   # write
  python3 tools/pin_labels_ld3.py --check --version v4.1.4 --canon 38.36              # every label agrees
"""
import argparse, hashlib, io, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
OLD = {"version": "v4.1.3", "md5": "f72e6762173dada604e0fe250e76f810", "bytes": 2990639, "date": "2026-09-26",
       "canon": "38.35"}
HISTORY = [("v4.1.0", "72187f6cf0fccdf8e9f4ec6ca5ce009c", 2982770), ("v4.1.1", "f095c0ce0e5a1d796d57fa5a5dd62f7d", 2985989),
           ("v4.1.2", "006aa9833f7a8b103ad27a289ab22fa9", 2987411), ("v4.1.3", "f72e6762173dada604e0fe250e76f810", 2990639)]
HIS_WORD = {"words": "Approved as is.", "said": "2026-09-26, in chat to the LD3 session, on the preview"}
CANONICAL = "8b76672fa3ca3cc33ca99e5b35fc25bd"   # the cross-surface md5, unchanged: no corpus literal moves


def rd(rel):
    return io.open(os.path.join(REPO, rel), encoding="utf-8", newline="").read()


def wr(rel, t):
    io.open(os.path.join(REPO, rel), "w", encoding="utf-8", newline="").write(t)


def once(t, old, new, where):
    n = t.count(old)
    if n != 1:
        raise SystemExit("ABORT: %s: %r occurs %d times, expected 1" % (where, old[:70], n))
    return t.replace(old, new)


def flagship():
    b = open(os.path.join(REPO, "site/combined.html"), "rb").read()
    return hashlib.md5(b).hexdigest(), len(b)


def num(n):
    return "{:,}".format(n)


def cf(v):
    return "project_canon_v%s.json" % v.replace(".", "_")


def entry(ver, date, md5, size, canon):
    table = "\n".join(["| | md5 | bytes |", "|---|---|---|"] +
                      ["| superseded — %s | `%s` | %s |" % (v, m, num(b)) for v, m, b in HISTORY] +
                      ["| **current — %s** | **`%s`** | **%s** |" % (ver, md5, num(size))])
    return (
        "## [%s] — %s\n\n"
        "**PATCH** by the invariants convention (the canon's `invariants` subtree is byte-identical), and **a page-design "
        "change only**: no objection's text moves. `site/combined.html` alone changes; the corpus JSON and the JSX are "
        "byte-identical to %s, and the cross-surface gate (`tools/xsurface_v4_1_0.py`) holds at `%s`. Both map sidecars "
        "regenerate byte for byte.\n\n"
        "The design lane's flagship marks (LD2's package, landed by LD3): every tier badge and tier filter carries its "
        "tier's mark, lit in that tier's own colour from the page's `TIERS`; the library's ladder sits beside its title "
        "and says its sentence once; a shared link to one objection plays that badge's mark once. On phones the badge "
        "row now keeps clear of the house layer's feedback link, which sat over the category label on the live page "
        "(31 of 82 cards at 390 px). Every mark region is generated by `icons/gen_icons.py` and gated by "
        "`tools/icons_regen_check.py`. Josiah approved it on the preview: \"%s\" Canon v%s.\n\n%s\n\n---\n\n"
        % (ver, date, OLD["version"], CANONICAL, HIS_WORD["words"], canon, table))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True)
    ap.add_argument("--canon", required=True)
    ap.add_argument("--date")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    md5, size = flagship()
    ver, bare = a.version, a.version.lstrip("v")
    if a.check:
        bad = []
        R, C, L, G = rd("README.md"), rd("CITATION.cff"), rd("site/libraries/index.html"), rd("CHANGELOG.md")
        for what, ok in (("README pin version", "| Version (pin) | `%s` |" % ver in R),
                         ("README pin md5", "| md5 | `%s` |" % md5 in R),
                         ("README pin size", "| Size | `%s` bytes |" % num(size) in R),
                         ("README libraries row", "flagship · pinned %s |" % ver in R),
                         ("README stable-at", "**Stable at %s** (canon v%s, file `%s`)" % (ver, a.canon, cf(a.canon)) in R),
                         ("README canon file x3", R.count(cf(a.canon)) == 3 and cf(OLD["canon"]) not in R),
                         ("README BibTeX", "version = {%s}," % bare in R),
                         ("CITATION version", 'version: "%s"' % bare in C),
                         ("badge", "<span>pinned %s</span>" % ver in L),
                         ("CHANGELOG entry", ("## [%s]" % ver) in G and ("**`%s`**" % md5) in G)):
            print("  %-22s %s" % (what, "ok" if ok else "FAIL"))
            bad += [] if ok else [what]
        print("PIN LABELS: %s" % ("GREEN" if not bad else "RED"))
        sys.exit(1 if bad else 0)
    if not a.date:
        sys.exit("--date is required to write")
    if md5 == OLD["md5"]:
        raise SystemExit("ABORT: site/combined.html is still the old pin")
    R = rd("README.md")
    R = once(R, "| Version (pin) | `%s` |" % OLD["version"], "| Version (pin) | `%s` |" % ver, "README")
    R = once(R, "| md5 | `%s` |" % OLD["md5"], "| md5 | `%s` |" % md5, "README")
    R = once(R, "| Size | `%s` bytes |" % num(OLD["bytes"]), "| Size | `%s` bytes |" % num(size), "README")
    R = once(R, "flagship · pinned %s |" % OLD["version"], "flagship · pinned %s |" % ver, "README")
    R = once(R, "**Stable at %s** (canon v%s, file `%s`). " % (OLD["version"], OLD["canon"], cf(OLD["canon"])),
             "**Stable at %s** (canon v%s, file `%s`). %s (%s) changes the flagship's page design only: the tier marks "
             "in their tiers' colours and the ladder beside the title, with no objection's text moved (see "
             "[`CHANGELOG.md`](CHANGELOG.md)). " % (ver, a.canon, cf(a.canon), ver, a.date), "README")
    n = R.count(cf(OLD["canon"]))
    if n != 2:
        raise SystemExit("ABORT: README names %s %d more times, expected 2" % (cf(OLD["canon"]), n))
    R = R.replace(cf(OLD["canon"]), cf(a.canon))
    R = once(R, "version = {%s}," % OLD["version"].lstrip("v"), "version = {%s}," % bare, "README")
    C = rd("CITATION.cff")
    C = once(C, 'version: "%s"' % OLD["version"].lstrip("v"), 'version: "%s"' % bare, "CITATION.cff")
    if a.date != OLD["date"]:
        C = once(C, 'date-released: "%s"' % OLD["date"], 'date-released: "%s"' % a.date, "CITATION.cff")
    L = rd("site/libraries/index.html")
    L = once(L, "<span>pinned %s</span>" % OLD["version"], "<span>pinned %s</span>" % ver, "site/libraries/index.html")
    G = rd("CHANGELOG.md")
    i = G.index("---\n\n## ") + len("---\n\n")
    G = G[:i] + entry(ver, a.date, md5, size, a.canon) + G[i:]
    wr("README.md", R); wr("CITATION.cff", C); wr("site/libraries/index.html", L); wr("CHANGELOG.md", G)
    print("PIN LABELS: %s -> %s  (%s / %s)" % (OLD["version"], ver, md5, num(size)))


if __name__ == "__main__":
    main()
